### ISSUE TITLE
Reaction Chamber not working when X amount of acceleration cards installed

### ISSUE THREAD

**Issue by AngelOfTheNight** [pedroksl/AdvancedAE#15]
As the title says If I go to either auto craft or regular craft a recipe

A few of the ones I have run into so far:

Example with making Charged Certus

In Reaction Chamber with 4 acceleration cards - Not working
![376001364-21675438-1071-4370-bc63-00e8be435370](https://github.com/user-attachments/assets/cbdcdde6-b8d1-41db-9ed6-d7263cd45853)

With 3 acceleration cards - Not working
![376001420-426c5db9-7ea9-4277-abeb-df5d823870ee](https://github.com/user-attachments/assets/783ab35e-8f97-41a6-8d76-453bff9a3c1c)

With 2 acceleration cards - Not working
![376001447-d85bb1f3-003a-4bc5-9489-85310197fd0e](https://github.com/user-attachments/assets/53527970-38db-4d74-a62f-f67e3bac7506)

With 1 acceleration cards - Working
![376001451-bab5f8ef-4205-4935-81a1-3af6694c7f76](https://github.com/user-attachments/assets/03b5cc37-2b80-4767-984c-3b39a8214f89)

Example with Matter Ball -> Singularity with 4 cards
![376001505-0bf21af9-98a4-4cc0-afe8-4b1b119d76fc](https://github.com/user-attachments/assets/ac580db6-52c0-4a24-be08-ede519712534)
 - Not Working

Works with only one card as well
![376001523-e7b92983-d901-4990-a0e4-351132386f32](https://github.com/user-attachments/assets/487a1a38-6bed-4ac0-a946-7527fabaf4fb)

Example to make Entro Crystal
4 cards - Not Working
![376001554-129026c7-de5e-4bde-bf22-5859643226fc](https://github.com/user-attachments/assets/c52ca77e-c280-404e-9926-b06f09fd6f6f)

3 Cards - Works (The crafting had already exported but it worked)
![376001563-e01a9c41-055b-4f46-a8df-0f30c3ec7225](https://github.com/user-attachments/assets/e9c62eac-d78f-4c92-879d-e5852da31cc3)

A crash log dump after trying to craft just in case this is helpful
[Minecraft ATM10 ExtendedAE Error.txt](https://github.com/user-attachments/files/17352763/Minecraft.ATM10.ExtendedAE.Error.txt)

**Comment by pedroksl** [comment]
Hi. After looking at the error it seems manually generated, which is expected because there’s nothing wrong with the behavior of the chambers. It there is with your system.

what acceleration cards do is decrease the amount of ticks required to complete the operation. AE2 machines don’t pull energy from the grid to fill their buffers, which means you need to have all of it available when requested. With 4 acceleration cards, the operation happens in 4 ticks. Which means that you need to have enough energy cells to support that. For instance, a singularity craft uses 1MFE. That is a consumption of 250k FE/t. Without energy cells to increase the available energy, the craft will not move. I wrote a whole section on the guide explaining the options for powering the chamber. I might add something to UI to make it clearer though, since you’re no the first person to be confused by crafts not moving.
