### ISSUE TITLE
Stock Output bus does not work

### ISSUE THREAD

**Issue by pixartist** [pedroksl/AdvancedAE#18]
Middle mouse button to set amount does not work and it outputs above the given amount (tested with reaction chamber)

**Comment by pedroksl** [comment]
Hi. Do you have middle click sort inventory installed or changed the pick block keybind? Middle click sort overrides my hot key and accepts the mouse event so they won’t work together unless the screen is black listed there. Changing the keybind should fix that.

As for the exporter not working with the text ion chamber, I need to take a look at that, because I haven’t tested that specific interaction.

**Comment by pedroksl** [comment]
Hey, just reporting back. I was able to reproduce the issue and already fixed it in dev. It will be up in the next release which should happen pretty soon. Thanks for the report!
