### ISSUE TITLE
make the mod able to load on server (1.0.0)

### ISSUE THREAD

**Issue by VaporeonScripts** [pedroksl/AdvancedAE#20]
neoforge .72

**Comment by VaporeonScripts** [comment]
https://mclo.gs/s2Ymmad

**Comment by pedroksl** [comment]
Hi. From these logs it doesn't look like my mod is the cause for your server crashing. The only time it is mentioned is when trying to apply a mixin which already exists since the first ever version of it.

* Does it load on previous versions of the mod?
* Do you have ExtendedAE installed alonside my mod?

**Comment by VaporeonScripts** [comment]
the issue has been fixes magically, so the mod isnt faulty, sorry
