### ISSUE TITLE
AppliedFlux dependency

### ISSUE THREAD

**Issue by Wizzerinus** [pedroksl/AdvancedAE#23]
Hey! This mod looks really neat but I don't really see why it would require AppliedFlux, since it's only used for the ME Throughput Monitor (and it can still work without Applied Flux). Can this be made into an optional dependency? Thanks!

**Comment by pedroksl** [comment]
It already is an optional dependency. Are you using the 1.0.0 version? That was a mistake and was fixed in the 1.0.1 version.

**Comment by Wizzerinus** [comment]
I'm on Minecraft 1.20 :(

**Comment by pedroksl** [comment]
Oh. I only removed the dependency in 1.21.1. The 1.20.1 version is not in development anymore. It also only contains the pattern provider and the quantum computer.

The reason why it still needs applied flux is because I had a ton of work making mixins and injecting into my own code when applied flux was installed. To port from neoforge back to forge would be basically the same work all over again. This takes my limited time from developing the mod to porting, and I don't think that's a productive use of it, unfortunately.

Hopefully you'll soon move on to a 1.21.1 pack and you'll be able to experience all the nice things I have for you in the newer version!

**Comment by Wizzerinus** [comment]
Reasonable enough. Thanks for letting me know!

According to the CF page, this mod is licensed under LGPL. as I'm not seeing the license in this repo, is this the actual case? if so I might look into fixing this in a fork (if I end up adding this into the pack I'm working on though, probably unlikely as I was mostly interested in the Throughput Monitor and Stock Export Bus but in case)

**Comment by pedroksl** [comment]
Interesting, I remember configuring the license, but I probably removed it accidentally somehow. I will add it back, thanks for the heads up.

And yeah, CF is correct, it's licensed under LGPL, so you could do that, if you wish.
