### ISSUE TITLE
Recipes in quantum computer reset if dimension is changed

### ISSUE THREAD

**Issue by shindaru** [pedroksl/AdvancedAE#25]
Hi I've added advancedAE to atm9 and have built my base in the mining dimension, as I have some stuff in the overworld I'm switching between and I've noticed that any recipes which are set to craft disappear when the world is changed

**Comment by pedroksl** [comment]
Hey. This issue is related to chunk loading. If you haven’t chunk loaded your base in the overworld, everything will be unloaded when you leave. You probably have ftb chunk loader in your pack, if so, just claim your chunks and then chunk load them. There should be tutorials for this online, if you can’t find the buttons.

**Comment by pedroksl** [comment]
I have two further questions.

1) did you claim chunks or force chunk load? Force chunk load has diagonal lines running across the shape.
2) what exactly did you force load? Was it only the cpu? I’m not sure how exactly ae2 deals with chunk loading, or what parts need to be loaded, so I tend to always load more than what I need. By that I mean loading the controller and cpus and potentially also the crafting machine and assemblers.

It would also help if you could send pictures if that doesn’t solve the issue. I’m positive this has nothing to do with my mod, I’m just trying to help you.
