### ISSUE TITLE
[1.20.1] Assigned a task to the terminal, but can’t cancel it.

### ISSUE THREAD

**Issue by vnj494** [pedroksl/AdvancedAE#3]
**Describe the bug**

Assigned a task, but can’t cancel it on the monitoring panel.

**How to reproduce the bug**

Using a quantum computer to assign synthesis tasks to the network.

**Additional details**
Bug happening on the allthemods9 modpack:0.3.0
ae2 15.2.9
advancedAE 0.3.1-1.20.1

**Which minecraft version are you using?**
1.20.1

**On which mod loaders does it happen?**
forge

**Comment by pedroksl** [comment]
After testing this in my development environment, I was unable to reproduce the issue, and could cancel it every time, unless I assigned multiple tasks for the same output, but this happens even without the Quantum Computer, so it's more likely an AE2 issue.

If that's not the case for the situation you're describing, it's more likely  some weird interaction with another mod's mixins, given that ATM9 has A LOT of mods. Probably needs more testing.

I need to be able to reproduce the issue to try and find a solution for it. So I might download ATM9 and try to debug with it. If I still can't make it happen here, there's not much I can do about it.

If you have any more details on how it happened and what exactly were you doing when it happened, it would be great.

**Comment by vnj494** [comment]
I am building a computer.
![1](https://github.com/user-attachments/assets/8e8c786b-d5d6-4abb-b393-80a2ac8ad352)
I wrote some synthesis recipes.
![9](https://github.com/user-attachments/assets/7b03c683-b5af-4dbe-ac94-a72f0b461aed)
Send a request to the network.
![10](https://github.com/user-attachments/assets/358fae0f-697a-4c4e-8f93-650b13333563)
Check the monitoring panel.
![11](https://github.com/user-attachments/assets/54cd609a-f299-443d-8848-5f751a239366)
I can’t cancel the synthesis, and I can’t monitor my synthesis progress.
This is a normal CPU process.
![13](https://github.com/user-attachments/assets/6c44c106-02fb-45ea-a69d-5cb916cac481)
![12](https://github.com/user-attachments/assets/46061512-946f-488b-899c-a75c0f19b816)

**Comment by pedroksl** [comment]
I tried copying as much as I could from your setup.
Two Quantum Computers at once, running crafting patterns instead of processing. Multiple patterns working at the same time, patterns with multiple steps, yet it still works fine in here.
![image](https://github.com/user-attachments/assets/072e11f8-dc84-4a1a-9a65-97f92d038aa7)

This leads me to assume it's some interaction with other mods in the modpack. I tried running the same mods as ATM9 but ran into some compatibility issues, and couldn't load it in debug mode. Trying to solve without debug tools would be like trying to write code in the dark. I'll try to think of some way to fix this, but for now there's not much I can do.

**Comment by vnj494** [comment]
Sorry to trouble you.

**Comment by Pecco-314** [comment]
I encountered the same issue. I can't monitor and cancel the tasks in ATM9.

**Comment by pedroksl** [comment]
Hi. The port of the quantum computer was kind of rushed because of a request made by the same user that created this thread, unfortunately it’s not being worked on as it makes sense to use my limited time on the new version that is currently officially added to ATM10. This mean that this issue is currently not a priority and I can’t make any promises in the way of fixing it.
