### ISSUE TITLE
Stock Export Bus ignores stock level when exporting to ME Chest

### ISSUE THREAD

**Issue by SeanLatimer** [pedroksl/AdvancedAE#35]
I'm unsure if this is a bug with the export bus itself, or just a weird interaction with AE itself.

I'm using an ME Chest to access my color applicator, my intention was to use the stock export bus with a crafting card to keep a stock of x paints whenever I put the applicator in the chest.

Exporting works but it does not obey the stock levels that have been set in the UI.

**Comment by pedroksl** [comment]
It’s potentially a weird interaction.

The ME chest is a very peculiar chest in the sense that it’s real inventory is actually the cell contained inside, not the contents of the cell. What this means is that when you try to insert items it wil handle that internally and fit it in the cell if possible. But when trying to read the contents (which is what the stock export bus does when trying to keep stock) it will only find the cell, and never be able to know how much is actually inside the ME chest.

I could potentially make a special case to try and fix this interaction, however for now you can probably solve this attaching the stock export bus to an interface connected to the chest. I’m not at home right now to test this, but it should be doable.

**Comment by SeanLatimer** [comment]
Just tested the bus onto an interface, it seems to result in the same issue of not obeying the stock level

**Comment by pedroksl** [comment]
This issue might be a bit deeper than I thought, then. For this to work the internal storage needs to be readable from the outside, and I’m not sure if AE2 provides that functionality (otherwise it would be the standard for these interactions, but normally you use interfaces for that and set to exactly what you want to be read). I will try to make a special case for this, because being inside the ae2 ecosystem has its perks but as these are two separate networks maybe it won’t be possible. I will report later with my findings.

**Comment by pedroksl** [comment]
I found a fix for this issue changing the way I check for external stock. Should work with not only ME Chests now, but any other AE2 storage type - except drives. Drives function differently as in they have an actual exposed inventory, but it only contains the cells and I'm not able to import/extract from them, so that won't work.

I'll push this with my next release, which should happen during the weekend.

Thanks for the report!

**Comment by pedroksl** [comment]
This feature has been release, I will close this issue now. Thanks again for the report.
