### ISSUE TITLE
Magnet card make armor sounds in creative invetory

### ISSUE THREAD

**Issue by YocyCraft** [pedroksl/AdvancedAE#38]
Reproduce:
1. Switch to creative mode
2. Wear a quantum helmet and add a magnet card
3. Open survival inventory tab on the bottom right corner
4. Every time when you pickup any item, armor sound would be made

**Comment by pedroksl** [comment]
Hey. This issue has been present for some time and annoyed me because most of my testing happens in creative mode, and that sound played even when just opening the inventory.

Thanks to your report, though, I was able to track it down. It wans't related to the Magnet Card, but any cards that consume energy passively, which is more than half. When opening the inventory with a different charge in the items in creative mode makes it think you have a different item and then triggers the sound of equipping it.

This has been fixed in dev in the next release. Thanks for the report.
