### ISSUE TITLE
[Minor? Issue] Entering water speeds up mining speed (even with bare hands) to almost instamine speeds

### ISSUE THREAD

**Issue by Desempregago** [pedroksl/AdvancedAE#39]
https://github.com/user-attachments/assets/ec254996-8b4a-47b0-9b3c-4fc44a8582d9

**Comment by Desempregago** [comment]
Modlist:
![image](https://github.com/user-attachments/assets/3e26af01-fb52-44f5-86fc-2c684ddd7a4c)

**Comment by pedroksl** [comment]
Hey. What are you equipping? Is there any enchant that removes penalty from mining underwater? Does the same happen if you submerge entirely, not with your head out of the water?

I found a couple of issues with this already, and fixed in code, but I'm looking for potentially more bugs involving this.

**Comment by Desempregago** [comment]
No, I’m not using anything enchanted, I’m just standing in a body of water.

**Comment by Desempregago** [comment]
I haven’t tested being fully submerged yet, might try it later today

**Comment by pedroksl** [comment]
Hey, Just a heads up, I just made a release with a bunch of fixed, this one is included, hopefully. Thanks for the report.
