### ISSUE TITLE
Quantum computer doesnt actaully craft items, but gets stuck on the last crafting steps.

### ISSUE THREAD

**Issue by Arthurabekat** [pedroksl/AdvancedAE#45]
![2024-11-23_01 02 51](https://github.com/user-attachments/assets/cc37d1ff-d584-44d1-8019-63b7604f16d4)

**Comment by Arthurabekat** [comment]
I also dont understand why its making so many cpus, like cpu1 2 3 4 5 6 and so on.

**Comment by pedroksl** [comment]
Dividing itself is the point of the quantum computer. One big cpu that can perform an infinite amount of tasks, as long as you have enough crafting storage left.

As for the crafts not finishing, it could be multiple reasons. Does it hang on any craft? Is it just a specific one that doesn't complete? I can see dusts being made, probably by requesters, are those being completed? If a specific recipe doesn't complete, there could be an issue with it especifically. For instance, you could have inserted it into the wrong pattern provider, or the pattern provider is failing to receive the items back. As the screenshot displays crafting recipes, you could have inserted it into a pattern provider pointing to a machine instead of molecular assembler/assembly matrix. There are too many possibilities for me to debug without enough information.

**Comment by Arthurabekat** [comment]
It got fixed after i made an assembler matrix and removed all other crafters👍

**Comment by pedroksl** [comment]
Interesting. I've had reports of the quantum computer not working well alongside other computers (be it a standard ae2 cpu or another quantum computer).

I haven't been able to reproduce it yet, though, so no luck on debugging it. But hopefully I can get that fixed too, soon. Thanks for the report.
