### ISSUE TITLE
ClassCastException when opening Advanced Pattern Provider

### ISSUE THREAD

**Issue by andriihorpenko** [pedroksl/AdvancedAE#56]
When you place and try to open APP, you get the `ClassCastException` error __on a dedicated server__.

**Mod version**: 1.0.2-1.20.1
**Log**: https://bytebin.lucko.me/3CQbEZtBSs

**Comment by pedroksl** [comment]
Hey. This is an issue with the applied flux integration. Can you try the extended version and check if that also breaks? I believe it won’t. If that’s the case you can use those while I work in releasing the fix for this.

**Comment by andriihorpenko** [comment]
I am not sure what do you mean by "extended version", may you elaborate?

**Comment by pedroksl** [comment]
There are two versions of the pattern provider, one with 36 slots and a normal one with 9. The bug you described happened with a 9 slots version. I just checked the code and the bug is, in fact, only related to the small version. I will release a fix as soon as I get home.

**Comment by pedroksl** [comment]
Hey, I just posted a fix for this issue. It wasn't what I originally believed. It was actually cause by not having applied flux installed. From your second commentary, I believe neither extended ae is installed. I will recommend you check those mods out, though, because they are awesome.

Anyway, I just published the fix to curseforge and it should be up pretty quickly. Thanks for the report.
