### ISSUE TITLE
Crafting job data is missing and crafting job cannot be cancelled

### ISSUE THREAD

**Issue by andriihorpenko** [pedroksl/AdvancedAE#58]
## Description
So these are actually two separate issues, which might be linked:
- The crafting job data is missing, meaning you cannot track the current state of the job: what is currently crafting, what is planned, etc.
- The "Cancel" button inside a crafting job menu is always inactive, making it impossible to cancel a job

## Demo
https://github.com/user-attachments/assets/2b726498-00e7-4f4b-afe8-99bc28d5d19a

## Impressions
I have a feeling that the data is actually there, it's just not fed to the container properly. What I'm looking at is what standby crafting menu with no active crafting jobs looks like.

## Metadata
- Minecraft version: 1.20.1
- Applied Energistics 2 version: 15.2.13
- AdvancedAE version: 1.0.4

**Comment by pedroksl** [comment]
Hey. As you have probably seen from my discord messages, I have been trying to track this issue down for quite some time. This issue was present in both 1.20.1 and 1.21.1, but it’s definitely more prevalent in 1.20.1.

I still haven’t been able to reproduce this by myself and up until now all reports happened on hit packs. World saves were also big enough to make sending the world to me barely not viable.


Seeing as you could finally reproduce it with just the base mods, I’ll try to do the same in dev. If I fail, can I somehow have that world file? It shouldn’t be big, considering it’s just a simple setup.

**Comment by andriihorpenko** [comment]
I was filming this on a custom modpack with ~170 handpicked mods, so I guess it will be quite hard to add all dependencies to the dev environment.
Lemme know if you would like a modpack profile from CurseForge, and also I can send you a flat level with this setup.

P.S. I might also try finding the root cause of the issue when I have a little more free time. Cheers.

**Comment by pedroksl** [comment]
Well, 170 mods is less than the 448 of atm9.

The mixin export got me nowhere, unless some mod is not injecting code and using accessors to change stuff instead.

Also, what you said about the crafting data is true. It exists, and the tooltips can prove it. They are also update overtime, so the menu is sending packets to the screen. However, for some reason, when you select it, it doesn’t update the main menu. I’m assuming somehow the serial id is lost or incompatible with the main screen’s serial map, but I don’t know for sure because of lack of debugging.

**Comment by andriihorpenko** [comment]
These sneaky bugs with no traces are the best. Okay, so while I am compiling a profile export for CF modpack and a clean save with minimal setup (will send them here in a bit), I'll spin up dev env as well, hopefully we will nuke this bug once and forever.

**Comment by pedroksl** [comment]
While you're at it, can you please update to 1.0.5? That version solves a bug related to the quantum computer. It was not working properly if you specifically selected it as the crafting cpu. This was due to a wrong cast, try to cast it directly to a crafting cpu instead of getting the cluster and asking it to create and return a new crafting cpu.

**Comment by andriihorpenko** [comment]
Just updated to 1.0.5, the issue remains the same, unfortunately.

**Comment by pedroksl** [comment]
I already knew it wouldn't solve it, I just wanted us to be relatively testing the same version. Thanks for all this, though.

**Comment by andriihorpenko** [comment]
Okay, so apparently, this is not an integration bug with another mod as I am able to reproduce it on a modpack with just AE2+AdvancedAE (with Gecko and Glodium as dependencies).

Do you need this tiny modpack with a save?

<img width="1186" alt="image" src="https://github.com/user-attachments/assets/aba16d07-9253-45d0-8c84-ee1230c3e818">

**Comment by pedroksl** [comment]
No need for the mod pack, but a save would be nice, if that wouldn’t be too much trouble.

**Comment by andriihorpenko** [comment]
Sure, here we go: [AdvancedAE Debug.zip](https://github.com/user-attachments/files/18012826/AdvancedAE.Debug.zip)

**Comment by pedroksl** [comment]
As explained in the discord message, this issue has been finally resolved. Thanks for all the help in trying to figure this one out, it was a tough one, for sure.
