### ISSUE TITLE
Flux Networks induction card does not power reaction chamber

### ISSUE THREAD

**Issue by jlp1528** [pedroksl/AdvancedAE#73]
I'm not sure whose bug this is. It doesn't work with the ExtendedAE circuit slicer either, but oddly enough it _does_ work with ExtendedAE's crystal assembler.

**Comment by pedroksl** [comment]
I just tested this in dev and it is working just fine. What is the context of your testing? Is this a modpack? What version are you using?

**Comment by jlp1528** [comment]
Direwolf20 for MC 1.21.1 pack version 1.8.0
I thought it was working but for some reason I had a cable next to it, probably for something I had moved or gotten rid of. Without the cable it doesn't work.
![2024-12-12_21 22 22](https://github.com/user-attachments/assets/040c31ec-ea50-4ab9-a5ca-77b2104dd6b7)
![2024-12-12_21 22 30](https://github.com/user-attachments/assets/96790a5c-715a-4e60-a65c-0654565cb676)
![2024-12-12_21 22 36](https://github.com/user-attachments/assets/201d8abe-5596-4435-8e06-666122e0b99a)

**Comment by pedroksl** [comment]
Oh. Insufficient power is different from having no power at all. You see how the progress bar is moving? You just don't have enough buffers to power it with 4 acceleration cards.

That recipe requires 1.3M fe, and with 4 cards it's processed in 4 ticks. This means it requires 325k fe/t if you want to go at full speed. You probably aren't generating enough to feed it. Try using less than 4 cards. Or wait for some time, because induction cards work similarly to all AE2 machines. They have a ramp up time. It will go faster as time goes. All this information is written on the guide that the tooltip is referring to. I would strongly advise using a full pattern provider block instead of an induction card for the chamber. The chamber can pull directly from FE cells without the need for the card, anyways.
