### ISSUE TITLE
7x7x7 quantum computer multiblock not forming

### ISSUE THREAD

**Issue by jlp1528** [pedroksl/AdvancedAE#76]
I formed a 3x3x3 and a 5x5x5 but can't seem to get 7x7x7 to work. :(

**Comment by pedroksl** [comment]
Please take a look at the tooltip of the quantum structure to know exactly the limit for your server. I changed the default to 7x7x7 and updated the in game guide but that doesn't reflect the actual config because of technical reasons. The tooltip should always be up to date, though. If that doesn't say 7x7x7 in the tooltip, you'll need to change the mod config in the configs file. If both of those are correct, then you possibly have a building mistake. Those happen a lot, specially when upgrading an existing quantum computer.

**Comment by jlp1528** [comment]
I might have to take a look at the configs, because I'm sure I built it correctly. I tried at least three times.

**Comment by jlp1528** [comment]
The config is set to 7. I don't understand what I'm doing wrong. I tried three times, including with nothing but the core and crafting units inside. Can you try building it in the direwolf20 1.21 mod pack?

**Comment by pedroksl** [comment]
Is the outside made with crafting structure or crafting units? Is there any chance you left a gap inside?

Can you use a copy paste gadget and send me the template code for your multiblock?

**Comment by jlp1528** [comment]
https://pste.ch/niwakabobe.json

**Comment by pedroksl** [comment]
Using your template in a dev world worked and the quantum computer formed.

This means there's nothing wrong with the structure as long as the configs are set correctly. I have a couple of question to try and understand what you're doing.

Is this on a server? If so, did you also set the configs on the server?
Did you put the quantum computer entirely contained in a chunk? Some weird behavior can happen when they aren't.

**Comment by jlp1528** [comment]
I will report this to the FTB team and reference this issue. direwolf20 1.21 pack. It was in a single chunk. SP world, config set to 7.
