### ISSUE TITLE
Throughput Monitor per minute setting

### ISSUE THREAD

**Issue by inputTTS** [pedroksl/AdvancedAE#77]
The throughput monitor calculates per minute throughput as the throughput in the last second times 60, rather than the average throughput over the last minute. I was hoping to use the throughput monitor to judge the pace of noisy farms like Mystical Agriculture, where since the plants are grown via ticks, some seconds there's a lot of harvests and other seconds there's none. This results in the throughput monitor jumping all over the place, rather than finding the mean amount per unit time.

**Comment by pedroksl** [comment]
No, you misunderstood the code.

```Java
// Normal update schedule
if (this.workRoutine == this.lastWorkRoutine) {
    var amountPerSecond = (getAmount() - amountAtLastUpdate) / timeInSeconds;
    this.lastReportedValue = Math.round(
            switch (this.workRoutine) {
                case TICK -> amountPerSecond / 20f;
                case SECOND -> amountPerSecond;
                case MINUTE -> amountPerSecond * 60f;
            });
    this.lastHumanReadableValue = getDisplayed().formatAmount(Math.abs(lastReportedValue), AmountFormat.SLOT);
} else {
    this.lastHumanReadableValue = "-";
}
```

`timeInSeconds` is how long it took since the last monitor update. `amountPerSecond` is the mean value over said period.
This gives me the amount that is being generated every second. The switch statement only calculates the amount that needs to be displayed based on the selected rate. The rate doesn't change the update rate of the monitor, it's fixed at around 20 seconds per update.

It doesn't keep history of all updates. Technically this could be an improvement at the cost of additional memory usage, but I would have to deal with wiping this history at times because the mean since the beggining of times, means nothing when you want to measure what's happening when you add another MA seed, for instance. If the history is too long it would take ages for that to do anything to the measure. For those reasons the monitor uses a fixed rate of 20s that should be long enough for most processes to output *something*, to be displayed.

**Comment by inputTTS** [comment]
I reply because it seemed like you misunderstood the core of my message because of my misunderstanding on how the code worked. One item I'm tracking oscillates between 409 and 495 per minute shown on monitor. That's such a large margin of error that I don't find the monitor useful, and resort to just using a timer and counting. This has applied to bees as well as MA, where I can't effectively use the throughput monitor to judge my daily or hourly production because of how bursty the production is and how the period of production can be longer than the sample time. 

If I understand you correctly it's taking the mean of the last twenty seconds, and then doing the appropriate math? Perhaps then slow up the update rate of the per minute mode to once per minute to get three times as many samples in the rate calculation, to help ease out some of the noise. 

If my described use case isn't something you'd like to support, that's understandable. But I wanted to make sure we were at least both on the same page with my issue and I do think it would be a valuable feature to the mod.

**Comment by pedroksl** [comment]
That's what I tried to explain in the second part of my reply, without going into technical details.

There were a few reasons why I implemented it the way I did:
- AE2 Ticking system is very complex and has minimum a maximum rates, with ramping/easing when moving between the two. These values cannot be changed, you can only choose between 5 options in an enum to determine the percentage of the ticking rate you'll be using.
- With a very slow ticking rate, and considering AE2 ramp time, it would take quite a long time before the monitor could provide an accurate reading. To me, because of this, 20 seconds is already too slow. The monitor takes at least that amount of time to reach steady state, despite my efforts to calculate accurately during ramping.
- Slow updates means a lot of stuff happens, and for some things (power, for instance) can lead to overflows. 20 seconds is already a lot for some things.

For very slow things, ideally, I would keep the ticking rate at 20s, but use some kind of memory system, like I told you in my first message, to provide a more accurate estimate. More information needs to be saved for this, alonside with the exact tick of the reading, but only on the slowest setting, while the others keep updating every monitor tick.

It's definitely doable with effort, but I'm not planning to implement it at the moment due to other priorities. I hope you understand.
