### ISSUE TITLE
Missing Recipes 1.20.1

### ISSUE THREAD

**Issue by ryu777mtg** [pedroksl/AdvancedAE#78]
Versions:

Forge 47.3.0

AdvancedAE-1.0.7-1.20.1
appliedenergistics2-forge-15.2.16
geckolib-forge-1.20.1-4.4.9
Glodium-1.20-1.5-forge

ExtendedAE-1.20-1.2.2-forge

emi-1.1.18+1.20.1+forge

There are no recipes for the following items unless hidden:

Quantum Infused Dust
Inscriber Quantum Press
Printed Quantum Circuit
Quantum Processor

All mods are installed with default settings.

Also trying to use REI RoughlyEnoughItems-12.1.785-forge results in no recipe for Quantum Ingots so bit confused

**Comment by pedroksl** [comment]
Hey. This is an EMI issue, not mine. EMI relies on JEI for a lot of recipes. That includes all inscriber related recipes. You'll notice that no presses at all appear in EMI standalone. Not just mine, but also MegaCell's, AppliedFlux and even AE2 itself. For those recipes to show up you have to use JEI alongside EMI. This will solve all of those missing recipes, since the Quantum Infused Dust is also an Inscriber (or Mekanism Crusher) recipe.

As for REI, it's currently not supported by the 1.20.1 version.

**Comment by ryu777mtg** [comment]
Ah thanks for clearing that up. Sorry didn't know their was an issue with EMI that couldn't read those particular recipes. Is something that is known by EMI author I wouldn't want to open another issue with them if it's already reported unless I just second the issue on the same post.

When using JEI with EMI is their a way to switch between the two interfaces or will one always take precedence over the other?
