### ISSUE TITLE
(Bug) Reaction Chamber Recipes Fluid Amounts Wrong in JEI

### ISSUE THREAD

**Issue by ArtpokeBr** [pedroksl/AdvancedAE#81]
As reported [here ](https://github.com/FTBTeam/FTB-Modpack-Issues/issues/6457) it seems like all Recipes from the Reaction Chamber displayed in JEI display exactly 1b of the input fluid instead of the correct amounts needed.

**Comment by pedroksl** [comment]
This issue only existed when FTB JEI Extras was the one implementing JEI integration. I have since taken over JEI support since [this version](https://github.com/pedroksl/AdvancedAE/releases/tag/1.1.7-1.21.1-neoforge), and made sure the fluids display the correct amounts. If FTB JEI Extras is in the pack, make sure it's in the latest version which should have my mod removed from it. (And also that my mod's version is the latest.)

**Comment by pedroksl** [comment]
I initially responded here talking about the issue not being present in my implementation of the JEI support, but I was wrong, so I deleted it. The JEI support was added in the 1.20.1 version and ported to 1.21.1. This has lead to an issue where the stack amounts were ignored due to a different implementation of the fluid ingredients in these versions. This has been fixed in dev and will be released soon.
![image](https://github.com/user-attachments/assets/64048b86-aac6-4fba-a33a-6f358546ce84)
