### ISSUE TITLE
for the speed of work

### ISSUE THREAD

**Issue by M0xiito** [pedroksl/AdvancedAE#9]
Please ask me to add some accelerated molecular collectors to the mod, since it takes me 5 hours of real time for huge crafts, and not only for me but also for most people.

**Comment by pedroksl** [comment]
What do you mean by accelerated mollecular collectors? Is it the same thing you asked in the other issue? Thereare no plans on implementing anything related to realizing crafts in this mod. There is already ExtendedAE for that. The Assembler matrix can run up to 1000 of crafting operations per tick. And if that's not your issue, it's probably just that you lack extra machines for stuff. For instance, you could have 4 of each machine instead of 1. If you have bottlenecks in your crafting system, you should look at the crafting status in your terminal to see what is the bottleneck. Then multiply the amount of machines running that process. The quantum computer already allows for you to run a ton of simultaneous machines, that's how you solve the crafting speed being low.

**Comment by M0xiito** [comment]
there is a lack of speed in molecular assemblers, not machines. and I really liked your mod, so I think you can create some accelerated versions

**Comment by pedroksl** [comment]
Unfortunately there is no way to accelerate crafters more than what ae2 allows. The only thing that can be done to speed crafting up is increasing the amount of concurrent crafts. That’s what the quantum computer does by increasing the amount of co-processors. On the other hand you need enough crafters to use all these co-processors. And that’s exactly what the Assembler Matrix from ExtendedAE does. I’m not just going to reimplement something that has already been done in another mod in the same ecosystem as mine.
